FROM gradle:6.7.0-jdk11
# gradle:6.7.0-jdk11 is gradle@sha256:33f85a6c2d3fd5f81987f66db3a3e379e562587e20b5ae404d8c4f7f62f37fb3

ARG UNAME=gradle
ARG UID=1000
ARG GID=1000

# Since the user and group 'gradle' exists we modify their GID and UID to match the host system
RUN usermod -u $UID -g $GID $UNAME
RUN chown -R $UNAME:$UNAME /home/gradle
USER $UNAME:$UNAME
WORKDIR /home/gradle

# Copy in entire project (of course this respects .dockerignore)
COPY --chown=gradle:gradle ./ ./

#ENTRYPOINT ""