name: Docker
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: soa-g2-student-service
  IMAGE_ID: docker.pkg.github.com/${{ github.repository }}
  VERSION: ${{ github.run_number }}

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Gradle project
        run: ./docker_build.sh

      - name: Build Docker image
        run: docker build . -t student-service

      - name: Naming, versioning and pushing image
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo IMAGE_ID=${{env.IMAGE_ID}}
          echo VERSION=${{env.VERSION}}
          docker tag 'student-service':'latest' ${{env.IMAGE_ID}}:${{env.VERSION}}
          docker push ${{env.IMAGE_ID}}:${{env.VERSION}}
         
