name: Docker
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: student-service
  IMAGE_ID: gchr.io/${{ github.repository }}/student-service
  VERSION: ${{ github.run_number }}

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Gradle project
        run: ./docker_build.sh

      - name: Build Docker image
        run: docker build . -t student-service

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Naming, versioning and pushing image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          echo IMAGE_ID=${{env.IMAGE_ID}}
          echo VERSION=${{env.VERSION}}
          docker tag ${{env.IMAGE_NAME}} ${{env.IMAGE_ID}}:${{env.VERSION}}
          docker push ${{env.IMAGE_ID}}:${{env.VERSION}}
         
